//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.10-b140802.1033 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.27 at 02:46:00 PM AEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "assign1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package uts.wsd.assign;
