//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.10-b140802.1033 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.27 at 02:32:05 PM AEST 
//


package uts.wsd.assign;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uts.wsd.assign package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ResponsesResponse_QNAME = new QName("assign1", "response");
    private final static QName _MeetingsMeeting_QNAME = new QName("assign1", "meeting");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uts.wsd.assign
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Polls }
     * 
     */
    public Polls createPolls() {
        return new Polls();
    }

    /**
     * Create an instance of {@link Poll }
     * 
     */
    public Poll createPoll() {
        return new Poll();
    }

    /**
     * Create an instance of {@link Meetings }
     * 
     */
    public Meetings createMeetings() {
        return new Meetings();
    }

    /**
     * Create an instance of {@link Meeting }
     * 
     */
    public Meeting createMeeting() {
        return new Meeting();
    }

    /**
     * Create an instance of {@link Responses }
     * 
     */
    public Responses createResponses() {
        return new Responses();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "assign1", name = "response", scope = Responses.class)
    public JAXBElement<String> createResponsesResponse(String value) {
        return new JAXBElement<String>(_ResponsesResponse_QNAME, String.class, Responses.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Meeting }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "assign1", name = "meeting", scope = Meetings.class)
    public JAXBElement<Meeting> createMeetingsMeeting(Meeting value) {
        return new JAXBElement<Meeting>(_MeetingsMeeting_QNAME, Meeting.class, Meetings.class, value);
    }

}
